name: reproduction.yml
on:
  push:
    branches:
      - main
jobs:
  reproduction:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install Dependencies
        run: npm ci
      - name: Reproduction
        continue-on-error: true
        shell: bash
        run: |-
          brew install coreutils
          timeout --preserve-status -s INT 3 npm start
